spring:
  datasource:
    url: jdbc:sqlite:sqlite-jpa.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    hikari:
      poolName: Hikari
      maximumPoolSize: 20
      minimumIdle: 5
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: 10.0.0.182
      port: 16379
      database: 0
      password: dnslin-redis
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate:
      sql: DEBUG
    org.hibernate.type.descriptor.sql: TRACE


server:
  port: 2341
  tomcat:
    max-http-form-post-size: 60000000
