spring:
  datasource:
    url: jdbc:sqlite:sql.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    hikari:
      # HikariCP settings
      poolName: Hikari
      maximumPoolSize: 20
      minimumIdle: 5
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: 10.0.0.182
      port: 16379
      database: 0
      password: dnslin-redis
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

# Logging level
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

server:
  port: 1230
  tomcat:
    max-http-form-post-size: 60000000
