name: Java CI with Maven

on:
  push:
    tags:
      - v4.*
      - v3.*
      - v2.*
      - v1.*
      - v0.*
  pull_request:
    branches: [ master ]
permissions:
  contents: write
jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v4
      - name: 设置JDK版本 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 缓存 Maven 依赖
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 编译代码
        run: mvn compile
      - name: Deploy the JAR file to the remote server
        uses: actions/checkout@v4
      - name: 设置JDK版本为21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 用Maven打成Jar包
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      - name: 发布Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/Scaffolding.jar
        env:
          GITHUB_REPOSITORY: dnslin/Scaffolding
      - name: 设置Docker USER 和 TOKEN
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: 设置Docker Build
        id: build
        uses: docker/setup-buildx-action@v1
      - name: 构建以及推送镜像
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/Scaffolding:latest
